name: Auto Pull Python Code from Big-Yellow-J

on:
  schedule:
    - cron: '0 0 * * *' # 每天 UTC 时间 00:00 运行（香港时间 08:00）
  workflow_dispatch: # 支持手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      # 检出目标仓库
      - name: Checkout target repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 获取完整历史以便合并
          token: ${{ secrets.ACCESS_TOKEN }} # 使用 PAT 检出

      # 配置 Git 用户信息
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

      # 获取源仓库的最新提交哈希
      - name: Get source repository latest commit
        run: |
          git ls-remote https://github.com/Big-Yellow-J/Big-Yellow-J.github.io.git master | awk '{print $1}' > current_commit.txt
          echo "Current source commit: $(cat current_commit.txt)"

      # 检查是否有更新
      - name: Check for updates
        id: check_updates
        run: |
          if [ -f .github/last_commit.txt ]; then
            LAST_COMMIT=$(cat .github/last_commit.txt)
            CURRENT_COMMIT=$(cat current_commit.txt)
            if [ "$LAST_COMMIT" != "$CURRENT_COMMIT" ]; then
              echo "New changes detected in source repository."
              echo "has_changes=true" >> $GITHUB_OUTPUT
            else
              echo "No changes detected in source repository."
              echo "has_changes=false" >> $GITHUB_OUTPUT
            fi
          else
            echo "No last_commit.txt found, treating as first sync."
            echo "has_changes=true" >> $GITHUB_OUTPUT
          fi

      # 拉取源仓库的 code/Python 目录（仅当有更新时）
      - name: Pull Python code from source repository
        if: steps.check_updates.outputs.has_changes == 'true'
        run: |
          git remote add source https://github.com/Big-Yellow-J/Big-Yellow-J.github.io.git
          git fetch source
          git checkout main # 目标仓库主分支（根据需要改为你的分支名）
          # 强制清空目标目录以确保源仓库内容为主
          rm -rf code/Python/*
          git checkout source/master -- code/Python/ # 拉取源仓库 master 分支的 code/Python
          git add code/Python/
          # 更新 last_commit.txt
          cat current_commit.txt > .github/last_commit.txt
          git add .github/last_commit.txt
          git commit -m "Auto-pull Python code from Big-Yellow-J/Big-Yellow-J.github.io (source overrides conflicts)" || echo "No changes to commit"

      # 推送更改到目标仓库
      - name: Push changes
        if: steps.check_updates.outputs.has_changes == 'true'
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${ACCESS_TOKEN}@github.com/shangxiaaabb/ProjectCode.git
          git push origin main
