name: AutoCodeSync

on:
  schedule:
    - cron: '0 0 * * *' # 每天 UTC 午夜运行
  workflow_dispatch: # 允许手动触发

# 防止并发运行
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      # 检出目标仓库
      - name: Checkout target repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.ACCESS_TOKEN }}

      # 配置 Git
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

      # 获取源仓库最新提交
      - name: Get source repository latest commit
        run: |
          git ls-remote https://github.com/Big-Yellow-J/Big-Yellow-J.github.io.git master | awk '{print $1}' > current_commit.txt
          echo "Current source commit: $(cat current_commit.txt)"

      # 检查更新
      - name: Check for updates
        id: check_updates
        run: |
          if [ -f .github/last_commit.txt ]; then
            LAST_COMMIT=$(cat .github/last_commit.txt)
            CURRENT_COMMIT=$(cat current_commit.txt)
            if [ "$LAST_COMMIT" != "$CURRENT_COMMIT" ]; then
              echo "has_changes=true" >> $GITHUB_OUTPUT
            else
              echo "has_changes=false" >> $GITHUB_OUTPUT
            fi
          else
            echo "has_changes=true" >> $GITHUB_OUTPUT
          fi

      # 同步文件
      - name: Sync Python folders
        if: steps.check_updates.outputs.has_changes == 'true'
        run: |
          # 添加源仓库并获取
          git remote add source https://github.com/Big-Yellow-J/Big-Yellow-J.github.io.git || true
          git fetch source

          # 重置到远程 main 分支
          git checkout main
          git fetch origin
          git reset --hard origin/main

          # 调试信息
          echo "Before sync - Local HEAD: $(git rev-parse HEAD)"
          echo "Before sync - Remote origin/main: $(git rev-parse origin/main)"

          # 获取源仓库 code/Python 下的子文件夹
          SUBFOLDERS=$(git ls-tree -d --name-only source/master code/Python 2>/dev/null || echo "")
          if [ -z "$SUBFOLDERS" ]; then
            echo "No subfolders found in code/Python."
            exit 0
          fi

          # 同步文件夹
          for folder in $SUBFOLDERS; do
            folder_name=$(basename "$folder")
            echo "Syncing folder: $folder_name"
            rm -rf "$folder_name"
            git checkout source/master -- "code/Python/$folder_name"
            mv "code/Python/$folder_name" ./
          done

          # 清理
          rm -rf code

          # 更新提交记录
          mkdir -p .github
          cat current_commit.txt > .github/last_commit.txt
          git add .

          # 提交更改
          if ! git diff-index --quiet HEAD --; then
            git commit -m "Auto-sync from source (commit $(cat current_commit.txt))"
          else
            echo "No changes to commit."
            exit 0
          fi

      # 强制推送
      - name: Force push changes
        if: steps.check_updates.outputs.has_changes == 'true'
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${ACCESS_TOKEN}@github.com/shangxiaaabb/ProjectCode.git
          git fetch origin
          echo "Before push - Local HEAD: $(git rev-parse HEAD)"
          echo "Before push - Remote origin/main: $(git rev-parse origin/main)"
          git push origin main --force
          echo "Push completed. Remote HEAD: $(git ls-remote origin main | awk '{print $1}')"