name: AutoCodeSync

on:
  schedule:
    - cron: '0 0 * * *' # 每天 UTC 时间 00:00 运行（香港时间 08:00）
  workflow_dispatch: # 支持手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      # 检出目标仓库
      - name: Checkout target repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 获取完整历史以便合并
          token: ${{ secrets.ACCESS_TOKEN }} # 使用 PAT 检出

      # 配置 Git 用户信息
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

      # 获取源仓库的最新提交哈希
      - name: Get source repository latest commit
        run: |
          git ls-remote https://github.com/Big-Yellow-J/Big-Yellow-J.github.io.git master | awk '{print $1}' > current_commit.txt
          echo "Current source commit: $(cat current_commit.txt)"

      # 检查是否有更新
      - name: Check for updates
        id: check_updates
        run: |
          if [ -f .github/last_commit.txt ]; then
            LAST_COMMIT=$(cat .github/last_commit.txt)
            CURRENT_COMMIT=$(cat current_commit.txt)
            if [ "$LAST_COMMIT" != "$CURRENT_COMMIT" ]; then
              echo "New changes detected in source repository."
              echo "has_changes=true" >> $GITHUB_OUTPUT
            else
              echo "No changes detected in source repository."
              echo "has_changes=false" >> $GITHUB_OUTPUT
            fi
          else
            echo "No last_commit.txt found, treating as first sync."
            echo "has_changes=true" >> $GITHUB_OUTPUT
          fi

      # 拉取源仓库 code/Python 下的所有子文件夹
      - name: Pull Python code folders from source repository
        if: steps.check_updates.outputs.has_changes == 'true'
        run: |
          git remote add source https://github.com/Big-Yellow-J/Big-Yellow-J.github.io.git
          git fetch source
          git checkout main # 目标仓库主分支（根据需要改为你的分支名）
          # 获取 code/Python 下的子文件夹列表
          SUBFOLDERS=$(git ls-tree -d source/master code/Python | awk '{print $NF}')
          if [ -z "$SUBFOLDERS" ]; then
            echo "No subfolders found in code/Python."
            exit 0
          fi
          # 强制清空目标仓库中对应的子文件夹（以源为主）
          for folder in $SUBFOLDERS; do
            rm -rf "$(basename $folder)"/*
          done
          # 拉取所有子文件夹
          git checkout source/master -- code/Python/*/
          # 移动子文件夹到根目录
          for folder in $SUBFOLDERS; do
            mv "code/Python/$(basename $folder)" "$(basename $folder)" || echo "Failed to move $folder, may already exist"
          done
          # 删除 code/Python 目录（如果不需要）
          rm -rf code/Python
          git add .
          # 更新 last_commit.txt
          cat current_commit.txt > .github/last_commit.txt
          git add .github/last_commit.txt
          git commit -m "Auto-pull Python code folders from Big-Yellow-J/Big-Yellow-J.github.io (source overrides conflicts)" || echo "No changes to commit"

      # 推送更改到目标仓库
      - name: Push changes
        if: steps.check_updates.outputs.has_changes == 'true'
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${ACCESS_TOKEN}@github.com/shangxiaaabb/ProjectCode.git
          git push origin main
